### ISSUE TITLE
[SE Issue] 

### ISSUE THREAD

**Issue by amiefoster** [learn-co-curriculum/react-hooks-fetch-crud-code-along#2]
### Canvas Link

https://learning.flatironschool.com/courses/4377/assignments/144462?module_item_id=303691

### Concern

In the second to last photo where you're passing {onDeleteItem} down as a prop. I believe it is supposed to be in src/components/Item.js however at the top of the reference photo it says it's in the src/components/ShoppingList.js. 

### Suggested Changes

Change src/components/ShoppingList.js to src/components/Item.js

**Comment by graciemcguire** [comment]
Hi @amiefoster !
I am struggling to find the issue. It looks to me that where we are passing `onDeleteItem` down it is in the Item component. 
```
// src/components/Item.js

// Deconstruct the onDeleteItem prop
function Item({ item, onUpdateItem, onDeleteItem }) {
  function handleDeleteClick() {
    // Call onDeleteItem, passing the deleted item
    fetch(`http://localhost:4000/items/${item.id}`, {
      method: "DELETE",
    })
      .then((r) => r.json())
      .then(() => onDeleteItem(item));
  }
  // ... rest of component
}
```

If you believe I've closed this issue down incorrectly, please reopen it and I will take another look. 
Thanks! 💙
