### ISSUE TITLE
Code Along Fails Test

### ISSUE THREAD

**Issue by leopards4life** [learn-co-curriculum/react-hooks-fetch-crud-code-along#7]
### Canvas Link

https://learning.flatironschool.com/courses/6191/assignments/228645?module_item_id=534062

### Concern

After completing the CRUD code along, npm test fails the test from ShoppingList.test.js line 47. I am not sure if this is an issue with the test, but I completed the code along and checked my code against the solution and am still failing this test.

**Comment by lizbur10** [comment]
Hi @leopards4life ! I was not able to recreate this problem - the tests were passing for me with the solution code - so I'm going to go ahead and close this issue. 

If you are still unable to get the tests passing, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Good luck! 💙
